import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QuickSubs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={
          inter.className +
          " bg-gradient-to-b from-[#504099] to-[#974EC3] min-h-screen text-white"
        }
      >
        <Toaster/>
        <main className="p-4 mx-auto max-w-2xl font-mono">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
